In [3]:
import numpy as np

In [23]:

marks=np.array([88,90,30,45,75])
new=np.array([])
new=marks+5
print(marks)
print(new)

[88 90 30 45 75]
[93 95 35 50 80]


In [24]:
marks+5

array([93, 95, 35, 50, 80])

In [ ]:
marks-5
print(marks)

[88 90 30 45 75]


indexing

In [34]:
marks[0]

np.int64(88)

In [37]:
print(marks[0])

88


In [38]:
print(marks[0])
print(marks[3])

88
45


In [41]:
print(marks[-1])
print(marks[-2])

75
45


traversing

In [42]:
for i in range(5):
    print(marks[i])


88
90
30
45
75


slicing

In [ ]:
marks[:2]

array([88, 90])

In [44]:
marks[1:4]

array([90, 30, 45])

In [45]:
marks=np.array([
    [85,78,90],[92,85,98],[76,82,80]]
)
print(marks)

[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [46]:
print(marks[0,0])

85


In [52]:
print(marks[0:2])
print(marks[0:2,0:2])

[[85 78 90]
 [92 85 98]]
[[85 78]
 [92 85]]


In [59]:
print(marks[2,1])
print(marks[0,2])
print(marks[1,0])
print(marks[0][2])

82
90
92
90


In [62]:
print(marks[1:,0])
print(marks[1:][0])

[92 76]
[92 85 98]


In [61]:
print(marks[0,:2])
print(marks[0][0:2])

[85 78]
[85 78]


concate

In [ ]:
b11=np.array([56,78,89])
b22=np.array([65,76,98])

comb=np.concatenate((b11,b22))
print(comb)

[56 78 89 65 76 98]


Split-always equal division 

In [65]:
print(np.split(comb,2))

for arr in np.split(comb,2):
    print(arr)



[array([56, 78, 89]), array([65, 76, 98])]
[56 78 89]
[65 76 98]


In [66]:
b1=np.array([[56,78,89],[34,45,68]])
b2=np.array([[85,78,90],[89,98,78]])

comb1=np.concatenate((b1,b2),axis=1)
print(comb1)
print("--------------")
comb0=np.concatenate((b1,b2),axis=0)
print(comb0)



[[56 78 89 85 78 90]
 [34 45 68 89 98 78]]
--------------
[[56 78 89]
 [34 45 68]
 [85 78 90]
 [89 98 78]]


search

In [81]:
marks=np.array([88,90,30,45,75])
print(np.where(marks==75))

(array([4]),)


In [87]:
mark=np.array([[85,78,90],
      [92,85,98],
      [76,82,80]])

print(np.where(mark==78))
print(mark)


(array([0]), array([1]))
[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [ ]:
mark=np.array([[85,78,90],
      [92,85,98],
      [76,82,80]])

print(np.where(mark<=80)) #gives index
print(mark)

(array([0, 2, 2]), array([1, 0, 2]))
[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [94]:
mark=np.array([[85,78,90],
      [92,85,98],
      [76,82,80]])

print(mark[np.where(mark>=80)]) #give exact value
print(mark)

[85 90 92 85 98 82 80]
[[85 78 90]
 [92 85 98]
 [76 82 80]]


Sort

In [ ]:
np.sort(mark)


array([[78, 85, 90],
       [85, 92, 98],
       [76, 80, 82]])

In [101]:
print(mark)

[[85 78 90]
 [92 85 98]
 [76 82 80]]


sort and reverse of whole array

In [102]:
np.sort(mark)

array([[78, 85, 90],
       [85, 92, 98],
       [76, 80, 82]])

In [99]:
np.sort(mark,axis=1)

array([[78, 85, 90],
       [85, 92, 98],
       [76, 80, 82]])

In [100]:
np.sort(mark,axis=0)

array([[76, 78, 80],
       [85, 82, 90],
       [92, 85, 98]])

In [96]:
np.sort(mark)[::-1]

array([[76, 80, 82],
       [85, 92, 98],
       [78, 85, 90]])